[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "KeepsakeChambers"
versionNumber = "1.0.3"
description = "Reducing amount of chambers needed to level up your keepsakes by a configurable amount, done by altering the increment amount for the keepsake."
websiteUrl = "https://github.com/excellent-ae/zannc-KeepsakeChambers"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"
SGG_Modding-ModUtil = "4.0.1"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[publish]
repository = "https://thunderstore.io"
communities = ["hades-ii"]

[publish.categories]
hades-ii = ["mods"]
